### ISSUE TITLE
Noto Color Emoji antialias issue in Firefox

### ISSUE THREAD

**Issue by guoyunhe** [openSUSE/fonts-config#12]
If user enabled antialias and set hintstyle to fullhint (in KDE font configuration), Noto Color Emoji will disappear in Firefox. (Chromium and Qt 5 applications are not affected.)

So I am thinking if we can force disable antialias and hinting for all color emoji fonts. These options seem meaningless for emoji fonts and will cause potential problems.

**Comment by marguerite** [comment]
already fixed in

https://github.com/marguerite/fonts-config-ng/blob/master/conf.d/21-emoji-rendering.conf

Sorry I was preparing the golang version, many long time bugs have been addressed and fixed there. I need to test the CJK part carefully (by reading debug logs not by eye) before merging
